cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false

spring:
  jpa:
    hibernate:
      ddl-auto: none
  cloud:
    function:
      definition: messages
    stream:
      bindings:
        messages-in-0:
          destination: stream-v0
          group: event-group
          content-type: application/json
          binder: kinesis
        messages-out-0:
          destination: stream-v0
          group: event-group
          content-type: application/json
          binder: kinesis
      kinesis:
        binder:
          checkpoint:
            #Set up so the AWS KCL can use dynamodb to manage multiple consumers ... so we dont have to :)
            table: checkpoint-table
          locks:
            table: locks-table
          # The following headers are propagated to the kinesis native message format.
          auto-add-shards: true
          min-shard-count: 16
